
spring:
  datasource:
    dynamic:
      datasource:
        master:
          dbName: mysql
          username: ${bot.mysql.username}
          password: ${bot.mysql.password}
          url: jdbc:mysql://${bot.mysql.host}:${bot.mysql.port}/${spring.datasource.dynamic.datasource.master.dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.haruhi.bot.entity
  mapper-locations: classpath:/mapper/*.xml

##################  以下配置项的值可改,上面不要动  ##################
bot:
  mysql:
    # mysql用户名
    username: root
    # mysql密码
    password: 123456
    # 主机
    host: 127.0.0.1
    # 端口 3306是mysql默认端口,一般不动
    port: 3306
    # 数据库名称(不用手动建,程序会自动建立)
    dbName: haruhibot
  gocq:
    # go-cqhttp正向ws代理地址,于go-cqhttp配置中的保持一致
    ws: ws://127.0.0.1:9909
server:
  # bot程序端口
  port: 9900
