mysql:
  # mysql用户名
  username: root
  # mysql密码
  password: 123456
  # 主机
  host: 127.0.0.1
  # 端口 3306是mysql默认端口,一般不动
  port: 3306
  # 数据库名称(不用手动建,程序会自动建立)
  dbName: haruhibot
gocq:
  # go-cqhttp正向ws代理地址,与go-cqhttp配置中的保持一致 必要
  ws: ws://127.0.0.1:9909
  # go-cqhttp正向http代理地址,与go-cqhttp配置中的保持一致 后面不要带斜杠 必要
  http: http://127.0.0.1:5700
  # 如果gocq设置了access-token 则此处与gocq的access-token保持一致 否则会连接失败
  access-token: 
bot:
  # bot程序端口
  port: 8081
  # 超级用户/管理员qq 只能填一个
  super-user:
  # bot的名字 只能填一个
  name: 春日酱
  # 搜图/识图功能需要配置这个项 Saucenao的API_KEY，通过 https://saucenao.com/user.php?page=search-api 注册获取 免费的
  search-image-key:
  bt-search: http://www.eclzz.guru
  agefans: https://www.agemys.vip
job:
  # 下载色图的定时爬虫 每15秒 enable是否开启这个定时任务 0非 1是
  downloadPixiv:
    cron: 0/15 * * * * ?
    enable: 0
    notice: 0
  # 订阅新闻job 每天7点 注意：如果关闭这个job，即使订阅了新闻也不会定时发新闻了
  news:
    cron: 0 0 7 * * ?
    enable: 1

#########################  以下配置项勿改  #########################

server:
  port: ${bot.port}
  servlet:
    context-path: /haruhi
spring:
  datasource:
    dynamic:
      datasource:
        master:
          dbName: mysql
          username: ${mysql.username}
          password: ${mysql.password}
          url: jdbc:mysql://${mysql.host}:${mysql.port}/${spring.datasource.dynamic.datasource.master.dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.haruhi.bot.entity
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.haruhi.bot.mapper: debug
env:
  active: dev
log:
  level: info
  path: ./logs

