
spring:
  datasource:
    dynamic:
      datasource:
        master:
          dbName: mysql
          username: ${bot.mysql.username}
          password: ${bot.mysql.password}
          url: jdbc:mysql://${bot.mysql.host}:${bot.mysql.port}/${spring.datasource.dynamic.datasource.master.dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.haruhi.bot.entity
  mapper-locations: classpath:/mapper/*.xml

##################  以下配置项的值可改,上面不要动  ##################
bot:
  mysql:
    username: root
    password: 123456
    host: 127.0.0.1
    port: 3306
    dbName: haruhibot
  gocq:
    ws: ws://127.0.0.1:9909
server:
  port: 9900
